package com.maeasoftworks.alfaconverter

import com.maeasoftworks.alfaconverter.core.conversions.Path
import com.maeasoftworks.alfaconverter.core.datatypes.xlsx.SNumber
import com.maeasoftworks.alfaconverter.core.datatypes.xlsx.SString
import com.maeasoftworks.alfaconverter.core.model.Table
import com.maeasoftworks.alfaconverter.core.model.Table.*

internal object ExampleTables {
	val tableFrom: Table by lazy { Table().fill {
		header(Cell(Path(0), 0) with SString("Column to bind 1"))
		put(   Cell(Path(0), 1) with SNumber(10))
		put(   Cell(Path(0), 2) with SNumber(20))
		put(   Cell(Path(0), 3) with SNumber(30))
		put(   Cell(Path(0), 4) with SNumber(40))
		put(   Cell(Path(0), 5) with SNumber(50))
		put(   Cell(Path(0), 6) with SNumber(60))
		put(   Cell(Path(0), 7) with SNumber(70))
		put(   Cell(Path(0), 8) with SNumber(80))
		put(   Cell(Path(0), 9) with SNumber(90))
		header(Cell(Path(1), 0) with SString("Column to bind 2"))
		put(   Cell(Path(1), 1) with SNumber(100))
		put(   Cell(Path(1), 2) with SNumber(200))
		put(   Cell(Path(1), 3) with SNumber(300))
		put(   Cell(Path(1), 4) with SNumber(400))
		put(   Cell(Path(1), 5) with SNumber(500))
		put(   Cell(Path(1), 6) with SNumber(600))
		put(   Cell(Path(1), 7) with SNumber(700))
		put(   Cell(Path(1), 8) with SNumber(800))
		put(   Cell(Path(1), 9) with SNumber(900))
		header(Cell(Path(2), 0) with SString("Will be split"))
		put(   Cell(Path(2), 1) with SString("a b c"))
		put(   Cell(Path(2), 2) with SString("b c a"))
		put(   Cell(Path(2), 3) with SString("c a b"))
		put(   Cell(Path(2), 4) with SString("a b c"))
		put(   Cell(Path(2), 5) with SString("b c a"))
		put(   Cell(Path(2), 6) with SString("c a b"))
		put(   Cell(Path(2), 7) with SString("a b c"))
		put(   Cell(Path(2), 8) with SString("b c a"))
		put(   Cell(Path(2), 9) with SString("c a b"))
		header(Cell(Path(3), 0) with SString("Will"))
		put(   Cell(Path(3), 1) with SNumber(1))
		put(   Cell(Path(3), 2) with SNumber(3))
		put(   Cell(Path(3), 3) with SNumber(1))
		put(   Cell(Path(3), 4) with SNumber(3))
		put(   Cell(Path(3), 5) with SNumber(1))
		put(   Cell(Path(3), 6) with SNumber(3))
		put(   Cell(Path(3), 7) with SNumber(1))
		put(   Cell(Path(3), 8) with SNumber(3))
		put(   Cell(Path(3), 9) with SNumber(1))
		header(Cell(Path(4), 0) with SString("be"))
		put(   Cell(Path(4), 1) with SNumber(2))
		put(   Cell(Path(4), 2) with SNumber(2))
		put(   Cell(Path(4), 3) with SNumber(2))
		put(   Cell(Path(4), 4) with SNumber(2))
		put(   Cell(Path(4), 5) with SNumber(2))
		put(   Cell(Path(4), 6) with SNumber(2))
		put(   Cell(Path(4), 7) with SNumber(2))
		put(   Cell(Path(4), 8) with SNumber(2))
		put(   Cell(Path(4), 9) with SNumber(2))
		header(Cell(Path(5), 0) with SString("merged"))
		put(   Cell(Path(5), 1) with SNumber(3))
		put(   Cell(Path(5), 2) with SNumber(1))
		put(   Cell(Path(5), 3) with SNumber(3))
		put(   Cell(Path(5), 4) with SNumber(1))
		put(   Cell(Path(5), 5) with SNumber(3))
		put(   Cell(Path(5), 6) with SNumber(1))
		put(   Cell(Path(5), 7) with SNumber(3))
		put(   Cell(Path(5), 8) with SNumber(1))
		put(   Cell(Path(5), 9) with SNumber(3))
		header(Cell(Path(6), 0) with SString("who?"))
		put(   Cell(Path(6), 1) with SString("me"))
		put(   Cell(Path(6), 2) with SString("me"))
		put(   Cell(Path(6), 3) with SString("me"))
		put(   Cell(Path(6), 4) with SString("me"))
		put(   Cell(Path(6), 5) with SString("me"))
		put(   Cell(Path(6), 6) with SString("me"))
		put(   Cell(Path(6), 7) with SString("me"))
		put(   Cell(Path(6), 8) with SString("me"))
		put(   Cell(Path(6), 9) with SString("me"))
	} }

	val tableTo: Table by lazy { Table().fill {
		header(Cell(Path(0), 0) with SString("Column to bind 1"))
		header(Cell(Path(1), 0) with SString("Column to bind 2"))
		header(Cell(Path(2), 0) with SString("Will be split"))
		header(Cell(Path(3), 0) with SString("Will"))
		header(Cell(Path(4), 0) with SString("be"))
		header(Cell(Path(5), 0) with SString("merged"))
		header(Cell(Path(6), 0) with SString("who?"))
	} }
}