spring:
  datasource:
    password: maeasoftworks
    username: maeasoftworks
    url: jdbc:postgresql://localhost:5432/converter
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQL10Dialect
  servlet:
    multipart:
      max-file-size: 20MB
      max-request-size: 20MB
      enabled: true

server:
  port: 8080

logging:
  level:
    org:
      docx4j: ERROR